# Generated by Django 2.2 on 2019-11-16 09:34

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
